@startuml
skinparam classAttributeIconSize 0

class Course{
    -teachers
    -students
}

class Teacher{
    -students
    -courses
}

class Student{
    -teachers
    -courses
}

Teacher "n" <--> "n" Student
Course "n" <--> "n" Teacher
Student "n" <--> "n" Course
@enduml