@startuml
skinparam classAttributeIconSize 0

class 氧气{
}

class 动物{
    +生命
    +新陈代谢(氧气，水)
    +繁殖()
}

class 水{

}

interface 飞翔 {
    +飞()
}

class 鸟{
    +下蛋()
}

class 翅膀{

}

class 雁群{

}

class 唐老鸭{
    +说话
}

interface 说话{
    +说话
}

class 气候 {

}

together {
    class 大雁{
        +下蛋()
        +飞()
    }

    class 鸭子{
        +下蛋()
    }

    class 企鹅{
        +下蛋
    }
}

动物 ..> 氧气
动物 ..> 水
鸟  --|> 动物
鸟 "1" *--> "2" 翅膀 :一个鸟有两个翅膀（组合）\n组合关系的双方是具有相同的生命周期的
大雁 --|> 鸟
鸭子 --|> 鸟
企鹅 --|> 鸟
大雁 ..|> 飞翔
雁群 "1" o--> "n" 大雁 : 大雁聚集在一起\n成了雁群（聚合）\n两者是独立的生命周期
唐老鸭 --|> 鸭子
唐老鸭 ..|> 说话
企鹅 --> 气候
@enduml