@startuml
title 爬虫管理系统时序图
actor "上游系统" as caller
actor "爬虫管理人员" as admin
participant "scrawlMng" as mng
participant "scrawlCore" as core
participant "redis" as redis
participant "数据库" as db
== 管理脚本 ==
mng -> mng:脚本的增删查改
== 爬虫 ==
mng -> core:分派爬虫job
core -> core:执行爬虫job
core -> db:数据入库
== 资源管理 ==
caller -> mng:查询数据
mng -> redis:查询缓存
redis -> mng:返回缓存的数据
mng -> caller:返回结果
@enduml